// Copyright dotBunny Inc. All Rights Reserved.
// See the LICENSE file at the repository root for more information.

#pragma once

#include "Assembly/Contexts/NAssemblyTaskGraphContext.h"
#include "Async/TaskGraphInterfaces.h"
#include "Assembly/NAssemblyTaskAnalytics.h"
#include "Assembly/Contexts/NPassContext.h"
#include "Assembly/Contexts/NVirtualWorldContext.h"

class UNAssemblyOperation;

/**
 * This task takes the generated NAssemblyGraphs generated by the pass and moves them to the top-level context,
 * as well as adds the generated cell hulls to the world-context for future generation collision detection.
 * 
 */
struct FNProcessPassTask
{
	explicit FNProcessPassTask(const TSharedPtr<FNPassContext>& PassContextPtr, 
		const TSharedPtr<FNVirtualWorldContext>& WorldContextPtr,
		const TSharedPtr<FNAssemblyTaskGraphContext>& TaskGraphContextPtr N_ASSEMBLY_ANALYTICS_CONSTRUCTOR);

	FORCEINLINE TStatId GetStatId() const { RETURN_QUICK_DECLARE_CYCLE_STAT(FNProcessPassTask, STATGROUP_TaskGraphTasks); }

	static ENamedThreads::Type GetDesiredThread() { return ENamedThreads::AnyNormalThreadNormalTask; }
	static ESubsequentsMode::Type GetSubsequentsMode() { return ESubsequentsMode::TrackSubsequents; }

	/** Executed by the task graph: moves collected graphs from the pass context up to the task-graph context. */
	void DoTask(ENamedThreads::Type CurrentThread, const FGraphEventRef& CompletionGraphEvent);

private:
	/** Pass-level collection being drained. */
	TSharedRef<FNPassContext> PassContextPtr;

	/** Virtual-world context that receives the new node hulls for downstream collision tests. */
	TSharedRef<FNVirtualWorldContext> WorldContextPtr;

	/** Top-level task-graph context that receives the drained graphs. */
	TSharedRef<FNAssemblyTaskGraphContext> TaskGraphContextPtr;

	N_ASSEMBLY_ANALYTICS_SHARED_REF
	N_ASSEMBLY_ANALYTICS_INDEX_LOCAL
};
