// Copyright dotBunny Inc. All Rights Reserved.
// See the LICENSE file at the repository root for more information.

#pragma once

#include "Generation/Contexts/NProcGenTaskGraphContext.h"
#include "Async/TaskGraphInterfaces.h"
#include "Generation/NProcGenTaskAnalytics.h"
#include "Generation/Contexts/NPassContext.h"
#include "Generation/Contexts/NWorldContext.h"

class UNProcGenOperation;

/**
 * This task takes the generated NProcGenGraphs generated by the pass and moves them to the top-level context,
 * as well as adds the generated cell hulls to the world-context for future generation collision detection.
 * 
 */
struct FNProcessPassContextTask
{
	explicit FNProcessPassContextTask(const TSharedPtr<FNPassContext>& PassContextPtr, 
		const TSharedPtr<FNWorldContext>& WorldContextPtr,
		const TSharedPtr<FNProcGenTaskGraphContext>& TaskGraphContextPtr, const TSharedPtr<FNProcGenTaskAnalytics>& AnalyticsPtr);

	FORCEINLINE TStatId GetStatId() const { RETURN_QUICK_DECLARE_CYCLE_STAT(FNCollectPassContextTask, STATGROUP_TaskGraphTasks); }

	static ENamedThreads::Type GetDesiredThread() { return ENamedThreads::AnyBackgroundThreadNormalTask; }
	static ESubsequentsMode::Type GetSubsequentsMode() { return ESubsequentsMode::TrackSubsequents; }

	/** Executed by the task graph: moves collected graphs from the pass context up to the task-graph context. */
	void DoTask(ENamedThreads::Type CurrentThread, const FGraphEventRef& CompletionGraphEvent);

private:
	/** Pass-level collection being drained. */
	TSharedRef<FNPassContext> PassContextPtr;
	
	TSharedRef<FNWorldContext> WorldContextPtr;

	/** Top-level task-graph context that receives the drained graphs. */
	TSharedRef<FNProcGenTaskGraphContext> TaskGraphContextPtr;
	
	TSharedRef<FNProcGenTaskAnalytics> AnalyticsPtr;
	int32 AnalyticsIndex = -1;
};
