name: 'Xperf Start Recording'
description: 'Start sample recording of metrics.'

runs:
  using: "composite"
  steps:    
    - name: StartMetrics
      shell: powershell
      run: |
        Write-Output "Starting recording  ..."
        & "xperf.exe" -on PROC_THREAD+LOADER+INTERRUPT+DPC+DISPATCHER+PROFILE -stackwalk PROFILE 
