name: 'Run Tests'
description: 'Runs defined unit tests via the UnrealEditor-Cmd.exe'

inputs:
  ue-installation:
    description: 'Path to UE installation'
    required: true
  tests:
    description: 'The test name prefix/category'
    required: true
  trace:
    type: boolean
    description: 'Enable tracing with Unreal Insights'
    required: true
    default: false

runs:
  using: "composite"
  steps:    
    - name: UnrealEditor-Cmd 
      shell: powershell
      run: |
        Write-Output "Building arguments ..."
        $CommandArgs = @('"${{ github.workspace }}\TestProject\NEXUS.uproject"', '-unattended', '-nopause', '-testexit="Automation Test Queue Empty"', '-ReportExportPath="${{ github.workspace }}\Staging\TestResults"', '-log')                      
        switch("${{ inputs.tests }}")
        {
          "Unit Tests"
          { 
            $CommandArgs += '-ExecCmds="Automation RunTest NEXUS.UnitTests;Quit"'
            $CommandArgs +=  '-nullrhi'    
          }
          "Performance Tests" 
          {
            $CommandArgs += '-ExecCmds="Automation RunTest NEXUS.PerfTests;Quit"'
            $CommandArgs +=  '-nullrhi'
          }
          "Functional Tests" 
          { 
            $CommandArgs += '-ExecCmds="Automation RunTest Tests.Nexus;Quit"'          
          }
        }  
        if(${{ inputs.trace }})
        {
          Write-Output "w/ Tracing"
          $CommandArgs += '-tracefile=${{ github.workspace }}\Staging\Trace.utrace'
        }     
        Write-Output "Starting Process ..."
        foreach ($arg in $CommandArgs) {        
            Write-Output "ARG: $arg"
        }
        & "${{ inputs.ue-installation }}\Engine\Binaries\Win64\UnrealEditor-Cmd.exe" $CommandArgs
    - name: Check Results
      shell: powershell
      run: |
        If (!(Test-Path "${{ github.workspace }}\Staging\TestResults\index.json"))
        { 
          Write-Output "::error ::Unable to find test results JSON."          
          exit -1
        }