# Local testing can be done by using 'bundle exec jekyll serve'.
# - Site settings {{ site.* }}

sass:
  style: compressed
title: NEXUS Framework
email: support@dotbunny.com

baseurl: ""
url: "https://nexus-framework.com"
description: A battle-tested collection of game-ready plugins for Unreal Engine.
docs: https://docs.nexus-framework.com

colors:
  primary: "#2b2b2b"
  background: "#2b2b2b"

github:
  home: https://github.com/dotBunny/NEXUS
  clone: https://github.com/dotBunny/NEXUS.git
  tree: https://github.com/dotBunny/NEXUS/tree/

project:
  changelog: https://github.com/dotBunny/NEXUS/blob/main/CHANGELOG.md
  overwatch: https://github.com/orgs/dotBunny/projects/6/views/1
  roadmap: https://github.com/orgs/dotBunny/projects/6/views/2
  issues: https://github.com/orgs/dotBunny/projects/6/views/3
  bugs: https://github.com/orgs/dotBunny/projects/6/views/9
  report: https://github.com/dotBunny/NEXUS/issues/new/choose

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - README.md  