name: 'Build Project'
description: 'Builds the project with the Unreal Engine Build.bat'

inputs:
  ue-installation:
    description: 'Path to UE installation'
    required: true
  target:
    description: 'The UE Target to build'
    default: 'NEXUSEditor'
    required: false    
  platform:
    description: 'The target platform'
    required: false
    default: 'Win64'
  config:
    description: 'The build config'
    required: false
    default: 'Development'
      
runs:
  using: "composite"
  steps:
    - name: Build.bat
      shell: powershell
      run: |
        & "${{ inputs.ue-installation}}\Engine\Build\BatchFiles\Build.bat" ${{ inputs.target }} ${{ inputs.platform }} ${{ inputs.config }} "${{ github.workspace }}\TestProject\NEXUS.uproject" -progress