name: 'Parse Results'
description: 'Parses the TestResults file and adds to the summary.'
            
runs:
  using: "composite"
  steps:    
    - name: Create markdown version of results and simplified CSV
      shell: powershell
      run: |
        $jsonPath = "${{ github.workspace }}\Staging\TestResults\index.json"
        $markdownPath = "${{ github.workspace }}\Staging\TestResults\index.md"
        $performancePath = "${{ github.workspace }}\Staging\TestResults\performance.csv"
        if (Test-Path -Path $markdownPath)
        {
          Remove-Item -Path "$markdownPath" -Force 
        }
        if (Test-Path -Path $performancePath)
        {
          Remove-Item -Path "$performancePath" -Force 
        }        

        if (Test-Path -Path $jsonPath)
        {
          Write-Output "Processing results from '$jsonPath' ..."
          $jsonContent = Get-Content -Path "$jsonPath"
          if ($jsonContent -eq $null -or $jsonContent -eq "")
          {
            Write-Output "No content found in '$jsonPath'."
            return
          }
          $json = $jsonContent | ConvertFrom-Json
          $device = $json.devices[0].deviceName
          $totalDuration = [Math]::Round($json.totalDuration, 6)
          $results_succeeded = $json.succeeded
          $results_succeededWithWarnings = $json.succeededWithWarnings
          $results_failed = $json.failed
          $results_notRun = $json.notRun
          $results_inProcess = $json.inProcess
          Write-Output "Tests ran on $device took $totalDuration seconds."
          Write-Output "Tests ran on **$device** took **$totalDuration seconds**." >> $markdownPath
          Write-Output "" >> $markdownPath
          Write-Output "## Results" >> $markdownPath
          Write-Output "" >> $markdownPath
          Write-Output "| :white_check_mark: **Pass** | :warning: **w/ Warning** | :x: **Failed** | :arrow_right_hook: **Skipped** | :finnadie: **Not Finished** |" >> $markdownPath
          Write-Output "| --- | --- | --- | --- | --- |" >> $markdownPath
          Write-Output "| $results_succeeded | $results_succeededWithWarnings | $results_failed | $results_notRun | $results_inProcess |" >> $markdownPath
          Write-Output "" >> $markdownPath
          Write-Output "## Tests" >> $markdownPath
          Write-Output "" >> $markdownPath
          Write-Output "| **Test** | **Duration (s)** | **Result** | **Warnings** | **Errors** | **Identifier** | **Timer (ms)** |" >> $markdownPath
          Write-Output "| --- | --- | --- | --- | --- | --- | --- |" >> $markdownPath
          foreach ($test in $json.tests) 
          {
              $test_fullTestPath = $test.fullTestPath.Replace(".", "::").Replace("Project::Functional Tests::", "")
              $test_state = $test.state
              if ($test_state -eq "Success")
              {
                  $test_state = ":green_circle: Pass"
              }
              elseif ($test_state -eq "Fail")
              {
                  $test_state = ":red_circle: Fail"
              }

              $test_warnings = $test.warnings
              $test_errors = $test.errors
              $test_duration = [Math]::Round($test.duration, 6)

              $test_identifier = "N/A"
              $test_timer = "N/A"
              if ($test.entries[0].event.type -eq "Info")
              {
                $event_message = $test.entries[0].event.message

                $event_message_id_end = $event_message.IndexOf(']') + 1

                $event_message_timer_start = $event_message_id_end + 1
                $event_message_time_end = $event_message.IndexOf(' ', $event_message_timer_start)
               
                if(![string]::IsNullOrEmpty($test_identifier) && ![string]::IsNullOrEmpty($test_timer))
                {
                  $test_identifier = $event_message.Substring(1, $event_message_id_end - 2)
                  $test_timer = $event_message.Substring($event_message_timer_start, $event_message_time_end - $event_message_timer_start)
                  Write-Output "$test_identifier,$test_timer" >> $performancePath
                }
              }

              Write-Output "| <code>$test_fullTestPath</code> | $test_duration | $test_state | $test_warnings | $test_errors | $test_identifier | $test_timer |" >> $markdownPath
          }
        }
        else
        {
          Write-Output "No results found at '$jsonPath'."
        }