name: 'Xperf Stop Recording'
description: 'Stop sample recording of metrics by session'

inputs:
  etl-file-name:
    description: 'Path to saved ETL file'
    required: true
    default: 'NPerformanceTests'

runs:
  using: "composite"
  steps:    
    - name: XperfStop
      shell: powershell
      run: |
        Write-Output "Stopping and saving session  ..."
        & "xperf.exe" -d ${{ github.workspace }}\Staging\${{ inputs.etl-file-name }}.etl
    - name: CollectPDBs
      shell: powershell
      run: |
        Write-Output "Collecting PDBs ..."
        Copy-Item -Path "${{ github.workspace }}\TestProject\Binaries\Win64\*.pdb" -Destination "${{ github.workspace }}\Staging\PDBs\" -Recurse