// Copyright dotBunny Inc. All Rights Reserved.
// See the LICENSE file at the repository root for more information.

#pragma once

// Required includes to implement this macro
#include "Menus/NToolsMenu.h"
#include "NEditorUtilityWidget.h"
#include "NEditorUtilityWidgetSubsystem.h"

/**
 * Declares a helper class that contributes a single Editor Utility Widget entry to the shared NEXUS Tools menu.
 *
 * Expands at file scope into a class named FNToosMenuEntry_<EntryIdentifier> with four static methods:
 * Register / Unregister (called from a module's startup / shutdown to install or remove the entry),
 * CreateEditorUtilityWindow (spawns the EUW tab when the menu item is clicked), and HasEditorUtilityWindow
 * (a query helper that returns whether the tab is currently open).
 *
 * Pair this with the N_TOOLS_MENU_ENTRY_EUW_METHOD_REGISTER / _UNREGISTER macros from a module's
 * StartupModule / ShutdownModule. Register is typically wired through UToolMenus::RegisterStartupCallback
 * so the entry is added once UToolMenus is ready.
 *
 * Place at file scope (outside any class) — typically in the editor module's public header next to the
 * module class itself.
 *
 * @param SectionName       String literal naming the section the entry belongs to (e.g. "Developer Overlay").
 *                          Entries sharing a section are grouped together in the Tools menu.
 * @param EntryIdentifier   Unstringified token used both as the FName identifier for the entry and as the
 *                          suffix on the generated helper class. Must be a valid C++ identifier and unique
 *                          across all tools-menu entries (e.g. EUW_NGuardian).
 * @param EntryDisplayName  FText (typically NSLOCTEXT) shown as the menu item's label.
 * @param EntryTooltip      FText (typically NSLOCTEXT) shown as the menu item's tooltip.
 * @param EntryIcon         FSlateIcon used for the menu item's leading icon.
 * @param Path              String literal asset path to the Editor Utility Widget to spawn when activated
 *                          (e.g. "/NexusGuardian/EditorResources/EUW_NGuardian.EUW_NGuardian").
 */
#define N_IMPLEMENT_TOOLS_MENU_EUW_ENTRY(SectionName, EntryIdentifier, EntryDisplayName, EntryTooltip, EntryIcon, Path) \
	class FNToosMenuEntry_##EntryIdentifier \
	{ \
		public: \
			/** Register the tool-menu entries with UToolMenus. */ \
			static void Register() { \
				auto EditorWindow = FNMenuEntry(); \
				EditorWindow.Section = TEXT(SectionName); \
				EditorWindow.Identifier = #EntryIdentifier; \
				EditorWindow.DisplayName = EntryDisplayName; \
				EditorWindow.Tooltip = EntryTooltip; \
				EditorWindow.Icon = EntryIcon; \
				EditorWindow.Execute = FExecuteAction::CreateStatic(&FNToosMenuEntry_##EntryIdentifier::CreateEditorUtilityWindow); \
				FNToolsMenu::AddMenuEntry(EditorWindow); \
			} \
			/** Unregister entries previously installed by Register. */ \
			static void Unregister() { \
				FNToolsMenu::RemoveMenuEntry(FName(#EntryIdentifier)); \
			} \
			/** Open the editor utility widget tab for this entry, creating it if necessary. */ \
			static void CreateEditorUtilityWindow() { \
				UNEditorUtilityWidget::SpawnTab(Path, FName(#EntryIdentifier)); \
			} \
			/** @return true if the editor utility widget tab is currently open. */ \
			static bool HasEditorUtilityWindow() { \
				UNEditorUtilityWidgetSubsystem* System = UNEditorUtilityWidgetSubsystem::Get(); \
				if (System == nullptr) return false; \
				const static FName SectionIdentifier = FName(#EntryIdentifier); \
				return System->HasWidget(SectionIdentifier); \
			} \
	};
	

/**
 * Resolves to the static Register function generated by N_IMPLEMENT_TOOLS_MENU_EUW_ENTRY for the given identifier.
 *
 * Use as either a direct call (append `()`) from StartupModule, or as a function pointer passed to
 * UToolMenus::RegisterStartupCallback so the entry is installed once the tool-menus subsystem is ready.
 *
 * @param EntryIdentifier The same identifier token passed to N_IMPLEMENT_TOOLS_MENU_EUW_ENTRY.
 */
#define N_TOOLS_MENU_ENTRY_EUW_METHOD_REGISTER(EntryIdentifier) FNToosMenuEntry_##EntryIdentifier::Register

/**
 * Resolves to the static Unregister function generated by N_IMPLEMENT_TOOLS_MENU_EUW_ENTRY for the given identifier.
 *
 * Typically invoked from ShutdownModule to remove the entry when the owning module is being torn down.
 *
 * @param EntryIdentifier The same identifier token passed to N_IMPLEMENT_TOOLS_MENU_EUW_ENTRY.
 */
#define N_TOOLS_MENU_ENTRY_EUW_METHOD_UNREGISTER(EntryIdentifier) FNToosMenuEntry_##EntryIdentifier::Unregister