// Copyright dotBunny Inc. All Rights Reserved.
// See the LICENSE file at the repository root for more information.

#pragma once

#include "UObject/ObjectMacros.h"

UENUM(BlueprintType)
enum ENDynamicRef : int32
{
	// ReSharper disable CppUE4CodingStandardNamingViolationWarning

	// Singles
	NDR_None							= 0 UMETA(DisplayName = "None"),
	NDR_Player							= 1 UMETA(DisplayName = "Player"),
	NDR_Enemy							= 2 UMETA(DisplayName = "Enemy"),
	NDR_NonPlayableCharacter			= 3 UMETA(DisplayName = "NPC"),
	
	// Locations
	NDR_Location_A 						= 32 UMETA(DisplayName = "Location A"),
	NDR_Location_B 						= 33 UMETA(DisplayName = "Location B"),
	NDR_Location_C 						= 34 UMETA(DisplayName = "Location C"),
	NDR_Location_D 						= 35 UMETA(DisplayName = "Location D"),
	NDR_Location_E 						= 36 UMETA(DisplayName = "Location E"),
	NDR_Location_F 						= 37 UMETA(DisplayName = "Location F"),
	NDR_Location_G 						= 38 UMETA(DisplayName = "Location G"),
	NDR_Location_H 						= 39 UMETA(DisplayName = "Location H"),
	NDR_Location_I 						= 40 UMETA(DisplayName = "Location I"),
	NDR_Location_J 						= 41 UMETA(DisplayName = "Location J"),
	NDR_Location_K 						= 42 UMETA(DisplayName = "Location K"),
	NDR_Location_L 						= 43 UMETA(DisplayName = "Location L"),
	NDR_Location_M 						= 44 UMETA(DisplayName = "Location M"),
	NDR_Location_N 						= 45 UMETA(DisplayName = "Location N"),
	NDR_Location_O 						= 46 UMETA(DisplayName = "Location O"),
	NDR_Location_P 						= 47 UMETA(DisplayName = "Location P"),
	NDR_Location_Q 						= 48 UMETA(DisplayName = "Location Q"),
	NDR_Location_R 						= 49 UMETA(DisplayName = "Location R"),
	NDR_Location_S 						= 50 UMETA(DisplayName = "Location S"),
	NDR_Location_T 						= 51 UMETA(DisplayName = "Location T"),
	NDR_Location_U 						= 52 UMETA(DisplayName = "Location U"),
	NDR_Location_V 						= 53 UMETA(DisplayName = "Location V"),
	NDR_Location_W 						= 54 UMETA(DisplayName = "Location W"),
	NDR_Location_X 						= 55 UMETA(DisplayName = "Location X"),
	NDR_Location_Y 						= 56 UMETA(DisplayName = "Location Y"),
	NDR_Location_Z 						= 57 UMETA(DisplayName = "Location Z"),

	// Objectives
	NDR_Objective_A 					= 58 UMETA(DisplayName = "Objective A"),
	NDR_Objective_B 					= 59 UMETA(DisplayName = "Objective B"),
	NDR_Objective_C 					= 60 UMETA(DisplayName = "Objective C"),
	NDR_Objective_D 					= 61 UMETA(DisplayName = "Objective D"),
	NDR_Objective_E 					= 62 UMETA(DisplayName = "Objective E"),
	NDR_Objective_F 					= 63 UMETA(DisplayName = "Objective F"),
	NDR_Objective_G 					= 64 UMETA(DisplayName = "Objective G"),
	NDR_Objective_H 					= 65 UMETA(DisplayName = "Objective H"),
	NDR_Objective_I 					= 66 UMETA(DisplayName = "Objective I"),
	NDR_Objective_J 					= 67 UMETA(DisplayName = "Objective J"),
	NDR_Objective_K 					= 68 UMETA(DisplayName = "Objective K"),
	NDR_Objective_L 					= 69 UMETA(DisplayName = "Objective L"),
	NDR_Objective_M 					= 70 UMETA(DisplayName = "Objective M"),
	NDR_Objective_N 					= 71 UMETA(DisplayName = "Objective N"),
	NDR_Objective_O 					= 72 UMETA(DisplayName = "Objective O"),
	NDR_Objective_P 					= 73 UMETA(DisplayName = "Objective P"),
	NDR_Objective_Q 					= 74 UMETA(DisplayName = "Objective Q"),
	NDR_Objective_R 					= 75 UMETA(DisplayName = "Objective R"),
	NDR_Objective_S 					= 76 UMETA(DisplayName = "Objective S"),
	NDR_Objective_T 					= 77 UMETA(DisplayName = "Objective T"),
	NDR_Objective_U 					= 78 UMETA(DisplayName = "Objective U"),
	NDR_Objective_V 					= 79 UMETA(DisplayName = "Objective V"),
	NDR_Objective_W 					= 80 UMETA(DisplayName = "Objective W"),
	NDR_Objective_X 					= 81 UMETA(DisplayName = "Objective X"),
	NDR_Objective_Y 					= 82 UMETA(DisplayName = "Objective Y"),
	NDR_Objective_Z 					= 83 UMETA(DisplayName = "Objective Z"),

	// Targets
	NDR_Target_A 						= 84 UMETA(DisplayName = "Target A"),
	NDR_Target_B 						= 85 UMETA(DisplayName = "Target B"),
	NDR_Target_C 						= 86 UMETA(DisplayName = "Target C"),
	NDR_Target_D 						= 87 UMETA(DisplayName = "Target D"),
	NDR_Target_E 						= 88 UMETA(DisplayName = "Target E"),
	NDR_Target_F 						= 89 UMETA(DisplayName = "Target F"),
	NDR_Target_G 						= 90 UMETA(DisplayName = "Target G"),
	NDR_Target_H 						= 91 UMETA(DisplayName = "Target H"),
	NDR_Target_I 						= 92 UMETA(DisplayName = "Target I"),
	NDR_Target_J 						= 93 UMETA(DisplayName = "Target J"),
	NDR_Target_K 						= 94 UMETA(DisplayName = "Target K"),
	NDR_Target_L 						= 95 UMETA(DisplayName = "Target L"),
	NDR_Target_M 						= 96 UMETA(DisplayName = "Target M"),
	NDR_Target_N 						= 97 UMETA(DisplayName = "Target N"),
	NDR_Target_O 						= 98 UMETA(DisplayName = "Target O"),
	NDR_Target_P 						= 99 UMETA(DisplayName = "Target P"),
	NDR_Target_Q 						= 100 UMETA(DisplayName = "Target Q"),
	NDR_Target_R 						= 101 UMETA(DisplayName = "Target R"),
	NDR_Target_S 						= 102 UMETA(DisplayName = "Target S"),
	NDR_Target_T 						= 103 UMETA(DisplayName = "Target T"),
	NDR_Target_U 						= 104 UMETA(DisplayName = "Target U"),
	NDR_Target_V 						= 105 UMETA(DisplayName = "Target V"),
	NDR_Target_W 						= 106 UMETA(DisplayName = "Target W"),
	NDR_Target_X 						= 107 UMETA(DisplayName = "Target X"),
	NDR_Target_Y 						= 108 UMETA(DisplayName = "Target Y"),
	NDR_Target_Z 						= 109 UMETA(DisplayName = "Target Z"),

	// Secrets
	NDR_Secret_A 						= 110 UMETA(DisplayName = "Secret A"),
	NDR_Secret_B 						= 111 UMETA(DisplayName = "Secret B"),
	NDR_Secret_C 						= 112 UMETA(DisplayName = "Secret C"),
	NDR_Secret_D 						= 113 UMETA(DisplayName = "Secret D"),
	NDR_Secret_E 						= 114 UMETA(DisplayName = "Secret E"),
	NDR_Secret_F 						= 115 UMETA(DisplayName = "Secret F"),
	NDR_Secret_G 						= 116 UMETA(DisplayName = "Secret G"),
	NDR_Secret_H 						= 117 UMETA(DisplayName = "Secret H"),
	NDR_Secret_I 						= 118 UMETA(DisplayName = "Secret I"),
	NDR_Secret_J 						= 119 UMETA(DisplayName = "Secret J"),
	NDR_Secret_K 						= 120 UMETA(DisplayName = "Secret K"),
	NDR_Secret_L 						= 121 UMETA(DisplayName = "Secret L"),
	NDR_Secret_M 						= 122 UMETA(DisplayName = "Secret M"),
	NDR_Secret_N 						= 123 UMETA(DisplayName = "Secret N"),
	NDR_Secret_O 						= 124 UMETA(DisplayName = "Secret O"),
	NDR_Secret_P 						= 125 UMETA(DisplayName = "Secret P"),
	NDR_Secret_Q 						= 126 UMETA(DisplayName = "Secret Q"),
	NDR_Secret_R 						= 127 UMETA(DisplayName = "Secret R"),
	NDR_Secret_S 						= 128 UMETA(DisplayName = "Secret S"),
	NDR_Secret_T 						= 129 UMETA(DisplayName = "Secret T"),
	NDR_Secret_U 						= 130 UMETA(DisplayName = "Secret U"),
	NDR_Secret_V 						= 131 UMETA(DisplayName = "Secret V"),
	NDR_Secret_W 						= 132 UMETA(DisplayName = "Secret W"),
	NDR_Secret_X 						= 133 UMETA(DisplayName = "Secret X"),
	NDR_Secret_Y 						= 134 UMETA(DisplayName = "Secret Y"),
	NDR_Secret_Z 						= 135 UMETA(DisplayName = "Secret Z"),

	// Spawns
	NDR_Spawn_A 						= 136 UMETA(DisplayName = "Spawn A"),
	NDR_Spawn_B 						= 137 UMETA(DisplayName = "Spawn B"),
	NDR_Spawn_C 						= 138 UMETA(DisplayName = "Spawn C"),
	NDR_Spawn_D 						= 139 UMETA(DisplayName = "Spawn D"),
	NDR_Spawn_E 						= 140 UMETA(DisplayName = "Spawn E"),
	NDR_Spawn_F 						= 141 UMETA(DisplayName = "Spawn F"),
	NDR_Spawn_G 						= 142 UMETA(DisplayName = "Spawn G"),
	NDR_Spawn_H 						= 143 UMETA(DisplayName = "Spawn H"),
	NDR_Spawn_I 						= 144 UMETA(DisplayName = "Spawn I"),
	NDR_Spawn_J 						= 145 UMETA(DisplayName = "Spawn J"),
	NDR_Spawn_K 						= 146 UMETA(DisplayName = "Spawn K"),
	NDR_Spawn_L 						= 147 UMETA(DisplayName = "Spawn L"),
	NDR_Spawn_M 						= 148 UMETA(DisplayName = "Spawn M"),
	NDR_Spawn_N 						= 149 UMETA(DisplayName = "Spawn N"),
	NDR_Spawn_O 						= 150 UMETA(DisplayName = "Spawn O"),
	NDR_Spawn_P 						= 151 UMETA(DisplayName = "Spawn P"),
	NDR_Spawn_Q 						= 152 UMETA(DisplayName = "Spawn Q"),
	NDR_Spawn_R 						= 153 UMETA(DisplayName = "Spawn R"),
	NDR_Spawn_S 						= 154 UMETA(DisplayName = "Spawn S"),
	NDR_Spawn_T 						= 155 UMETA(DisplayName = "Spawn T"),
	NDR_Spawn_U 						= 156 UMETA(DisplayName = "Spawn U"),
	NDR_Spawn_V 						= 157 UMETA(DisplayName = "Spawn V"),
	NDR_Spawn_W 						= 158 UMETA(DisplayName = "Spawn W"),
	NDR_Spawn_X 						= 159 UMETA(DisplayName = "Spawn X"),
	NDR_Spawn_Y 						= 160 UMETA(DisplayName = "Spawn Y"),
	NDR_Spawn_Z 						= 161 UMETA(DisplayName = "Spawn Z"),

	// Enemies
	NDR_Enemy_A 						= 162 UMETA(DisplayName = "Enemy A"),
	NDR_Enemy_B 						= 163 UMETA(DisplayName = "Enemy B"),
	NDR_Enemy_C 						= 164 UMETA(DisplayName = "Enemy C"),
	NDR_Enemy_D 						= 165 UMETA(DisplayName = "Enemy D"),
	NDR_Enemy_E 						= 166 UMETA(DisplayName = "Enemy E"),
	NDR_Enemy_F 						= 167 UMETA(DisplayName = "Enemy F"),
	NDR_Enemy_G 						= 168 UMETA(DisplayName = "Enemy G"),
	NDR_Enemy_H 						= 169 UMETA(DisplayName = "Enemy H"),
	NDR_Enemy_I 						= 170 UMETA(DisplayName = "Enemy I"),
	NDR_Enemy_J 						= 171 UMETA(DisplayName = "Enemy J"),
	NDR_Enemy_K 						= 172 UMETA(DisplayName = "Enemy K"),
	NDR_Enemy_L 						= 173 UMETA(DisplayName = "Enemy L"),
	NDR_Enemy_M 						= 174 UMETA(DisplayName = "Enemy M"),
	NDR_Enemy_N 						= 175 UMETA(DisplayName = "Enemy N"),
	NDR_Enemy_O 						= 176 UMETA(DisplayName = "Enemy O"),
	NDR_Enemy_P 						= 177 UMETA(DisplayName = "Enemy P"),
	NDR_Enemy_Q 						= 178 UMETA(DisplayName = "Enemy Q"),
	NDR_Enemy_R 						= 179 UMETA(DisplayName = "Enemy R"),
	NDR_Enemy_S 						= 180 UMETA(DisplayName = "Enemy S"),
	NDR_Enemy_T 						= 181 UMETA(DisplayName = "Enemy T"),
	NDR_Enemy_U 						= 182 UMETA(DisplayName = "Enemy U"),
	NDR_Enemy_V 						= 183 UMETA(DisplayName = "Enemy V"),
	NDR_Enemy_W 						= 184 UMETA(DisplayName = "Enemy W"),
	NDR_Enemy_X 						= 185 UMETA(DisplayName = "Enemy X"),
	NDR_Enemy_Y 						= 186 UMETA(DisplayName = "Enemy Y"),
	NDR_Enemy_Z 						= 187 UMETA(DisplayName = "Enemy Z"),

	// Pickup
	NDR_Pickup_A 						= 188 UMETA(DisplayName = "Pickup A"),
	NDR_Pickup_B 						= 189 UMETA(DisplayName = "Pickup B"),
	NDR_Pickup_C 						= 190 UMETA(DisplayName = "Pickup C"),
	NDR_Pickup_D 						= 191 UMETA(DisplayName = "Pickup D"),
	NDR_Pickup_E 						= 192 UMETA(DisplayName = "Pickup E"),
	NDR_Pickup_F 						= 193 UMETA(DisplayName = "Pickup F"),
	NDR_Pickup_G 						= 194 UMETA(DisplayName = "Pickup G"),
	NDR_Pickup_H 						= 195 UMETA(DisplayName = "Pickup H"),
	NDR_Pickup_I 						= 196 UMETA(DisplayName = "Pickup I"),
	NDR_Pickup_J 						= 197 UMETA(DisplayName = "Pickup J"),
	NDR_Pickup_K 						= 198 UMETA(DisplayName = "Pickup K"),
	NDR_Pickup_L 						= 199 UMETA(DisplayName = "Pickup L"),
	NDR_Pickup_M 						= 200 UMETA(DisplayName = "Pickup M"),
	NDR_Pickup_N 						= 201 UMETA(DisplayName = "Pickup N"),
	NDR_Pickup_O 						= 202 UMETA(DisplayName = "Pickup O"),
	NDR_Pickup_P 						= 203 UMETA(DisplayName = "Pickup P"),
	NDR_Pickup_Q 						= 204 UMETA(DisplayName = "Pickup Q"),
	NDR_Pickup_R 						= 205 UMETA(DisplayName = "Pickup R"),
	NDR_Pickup_S 						= 206 UMETA(DisplayName = "Pickup S"),
	NDR_Pickup_T 						= 207 UMETA(DisplayName = "Pickup T"),
	NDR_Pickup_U 						= 208 UMETA(DisplayName = "Pickup U"),
	NDR_Pickup_V 						= 209 UMETA(DisplayName = "Pickup V"),
	NDR_Pickup_W 						= 210 UMETA(DisplayName = "Pickup W"),
	NDR_Pickup_X 						= 211 UMETA(DisplayName = "Pickup X"),
	NDR_Pickup_Y 						= 212 UMETA(DisplayName = "Pickup Y"),
	NDR_Pickup_Z 						= 213 UMETA(DisplayName = "Pickup Z"),

	// Items
	NDR_Item_A 							= 214 UMETA(DisplayName = "Item A"),
	NDR_Item_B 							= 215 UMETA(DisplayName = "Item B"),
	NDR_Item_C 							= 216 UMETA(DisplayName = "Item C"),
	NDR_Item_D 							= 217 UMETA(DisplayName = "Item D"),
	NDR_Item_E 							= 218 UMETA(DisplayName = "Item E"),
	NDR_Item_F 							= 219 UMETA(DisplayName = "Item F"),
	NDR_Item_G 							= 220 UMETA(DisplayName = "Item G"),
	NDR_Item_H 							= 221 UMETA(DisplayName = "Item H"),
	NDR_Item_I 							= 222 UMETA(DisplayName = "Item I"),
	NDR_Item_J 							= 223 UMETA(DisplayName = "Item J"),
	NDR_Item_K 							= 224 UMETA(DisplayName = "Item K"),
	NDR_Item_L 							= 225 UMETA(DisplayName = "Item L"),
	NDR_Item_M 							= 226 UMETA(DisplayName = "Item M"),
	NDR_Item_N 							= 227 UMETA(DisplayName = "Item N"),
	NDR_Item_O 							= 228 UMETA(DisplayName = "Item O"),
	NDR_Item_P 							= 229 UMETA(DisplayName = "Item P"),
	NDR_Item_Q 							= 230 UMETA(DisplayName = "Item Q"),
	NDR_Item_R 							= 231 UMETA(DisplayName = "Item R"),
	NDR_Item_S 							= 232 UMETA(DisplayName = "Item S"),
	NDR_Item_T 							= 233 UMETA(DisplayName = "Item T"),
	NDR_Item_U 							= 234 UMETA(DisplayName = "Item U"),
	NDR_Item_V 							= 235 UMETA(DisplayName = "Item V"),
	NDR_Item_W 							= 236 UMETA(DisplayName = "Item W"),
	NDR_Item_X 							= 237 UMETA(DisplayName = "Item X"),
	NDR_Item_Y 							= 238 UMETA(DisplayName = "Item Y"),
	NDR_Item_Z 							= 239 UMETA(DisplayName = "Item Z"),

	NDR_Max								= 240 UMETA(Hidden)
	
	// ReSharper restore CppUE4CodingStandardNamingViolationWarning
};