name: 'Run UAT'
description: 'Runs the defined command with UAT'

inputs:
  ue-uat:
    description: 'The path to the RunUAT.bat'
    default: 'C:\Program Files\Epic Games\UE_5.6\Engine\Build\BatchFiles\RunUAT.bat'
    required: false
  command:
    description: 'The primary command to run with UAT'
    required: true    
  additional-arguments:
    description: 'Any additional arguments to pass to the command'
    required: false  
    default: ''

runs:
  using: "composite"
  steps:    
    - name: RunUAT 
      shell: powershell
      run: |
        Write-Output "Run UAT..."
        & "${{ inputs.ue-uat }}" ${{ inputs.command }} -project="${{ github.workspace }}\TestProject\NEXUS.uproject" ${{ inputs.additional-arguments }}