name: 'Run UAT'
description: 'Runs the defined command with UAT'

inputs:
  ue-installation:
    description: 'Path to UE installation'
    required: true
  command:
    description: 'The primary command to run with UAT'
    required: true    
  additional-arguments:
    description: 'Any additional arguments to pass to the command'
    required: false  
    default: ''

runs:
  using: "composite"
  steps:  
    - name: Add UAT Matcher
      shell: powershell
      run: |
        echo "::add-matcher::${{ github.workspace }}\.github\problem-matchers\uat.json"
    - name: RunUAT
      shell: powershell
      run: |
        & "${{ inputs.ue-installation }}\Engine\Build\BatchFiles\RunUAT.bat" ${{ inputs.command }} -project="${{ github.workspace }}\TestProject\NEXUS.uproject" ${{ inputs.additional-arguments }}
    - name: Remove UAT Matcher
      shell: powershell
      run: |
        echo "::remove-matcher::${{ github.workspace }}\.github\problem-matchers\uat.json"