name: BuildCookRun (Development)

on:  
  schedule:
    - cron: '0 9 * * *' # 5:00 AM EST - Farm Not Busy

jobs:
  BuildCookRun:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Get Branch Settings
        id: settings
        run: |
          $json = Get-Content .github/branch.json | ConvertFrom-Json
          $installation = $json.installation
          echo "ue=$installation" >> $env:GITHUB_OUTPUT
        shell: powershell

      - name: Clean workspace
        uses: ./.github/actions/workspace-clean

      - name: Build project
        uses: ./.github/actions/build-project
        with:
          ue-installation: ${{ steps.settings.outputs.ue }}

      - name: Run UAT
        uses: ./.github/actions/ue-uat
        with:
          ue-installation: ${{ steps.settings.outputs.ue }}
          command: 'BuildCookRun'
          additional-arguments: '-target=NEXUS -platform=Win64 -clientconfig=Development -cook -stage -package -build -pak -archive -archivedirectory="${{ github.workspace }}\Staging\Build"'
    