name: Functional Tests
run-name: Functional Tests (Tests.Nexus)

on:  
  schedule:
    - cron: '0 8 * * *' # 4:00 AM EST - Farm Not Busy

jobs:
  FunctionalTests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Clean workspace
        uses: ./.github/actions/workspace-clean

      - name: Build project
        uses: ./.github/actions/build-project

      - name: Run functional tests
        uses: ./.github/actions/ue-cmd-tests
        with:
          tests: 'Functional Tests'

      - name: Parse UE log
        if: always()
        uses: ./.github/actions/ue-parse-log

      - name: Parse test results
        if: always()
        uses: ./.github/actions/ue-parse-results

      - name: Gather and upload artifacts
        if: always()
        uses: ./.github/actions/upload-artifacts
        with:
          artifact-name: 'schedule-functional-tests-${{ github.run_number }}'

      # This needs to be on the workflow to ensure it has access to the GITHUB_STEP_SUMMARY
      - name: Update summary
        if: always()
        shell: powershell
        run: |
          $markdownPath = "${{ github.workspace }}\Staging\TestResults\index.md"
          if(Test-Path -Path $markdownPath)
          {
            $markdownLines = Get-Content -Path $markdownPath
            $outputPath = $env:GITHUB_STEP_SUMMARY
            Write-Output "Updating GITHUB_STEP_SUMMARY with $outputPath."
            foreach ($line in $markdownLines) 
            {
              Write-Output "$line" >> $outputPath
            }
          }